// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coord_descent_cpp
Rcpp::List coord_descent_cpp(arma::vec& w, const arma::mat& z, double lambda, uint max_iters);
RcppExport SEXP _sparseglm_coord_descent_cpp(SEXP wSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< uint >::type max_iters(max_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_descent_cpp(w, z, lambda, max_iters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sparseglm_coord_descent_cpp", (DL_FUNC) &_sparseglm_coord_descent_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparseglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
