# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_descent_cpp <- function(w, z, lambda, max_iters) {
    .Call(`_sparseglm_coord_descent_cpp`, w, z, lambda, max_iters)
}

